### ISSUE TITLE
automatically make attributes pub ? 

### ISSUE THREAD

**Issue by Carreau** [google/evcxr#10]
Seem like you already detect when fields of structs are not pub, with the error message:

> Items currently need to be explicitly made pub along with all fields of structs.

Could it be possible with syn to rewrite the AST and add `pub` automatically ?

**Comment by davidlattimore** [comment]
Eventually I'd like to. Unfortunately it doesn't look practical to me until [proc_macro2 exposes span](https://github.com/alexcrichton/proc-macro2/blob/master/src/lib.rs) information. Currently the spans on AST nodes don't have provide any way to find out where in original source they came from... unless you build like:
RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo build
but I don't want to ask people to build like that.

Something else I'd considered, was just recompiling everything every time so that all the code is "in one crate". Not sure if that might have implications for type IDs though, which could affect the ability to get variable values back out of the variable map.

**Comment by davidlattimore** [comment]
With release 0.4.0 and onwards, I changed the execution model that Evcxr uses, so that all code is now a single crate instead of a separate crate for each bit of code. As a result, pub is no longer needed :)
