### ISSUE TITLE
Support for crates with different library name

### ISSUE THREAD

**Issue by jonasbb** [google/evcxr#15]
I tried to use the crate [`prettytable-rs`](https://crates.io/crates/prettytable-rs) in evcxr_jupyter, however I cannot get it to work. I think the problem is that even though the crate name is `prettytable-rs`, the library is only called `prettytable` (you use `extern crate prettytable;`).

Writing `:dep prettytable-rs = "0.7"` prints 
```
can't find crate for `prettytable_rs`
```
on the terminal. Trying `extern crate prettytable;` results in the error
```
error: no matching package named `prettytable` found
```
being shown in the Jupyter notebook.

**Comment by davidlattimore** [comment]
Thanks for filing this. I didn't know it was possible to rename a library like that. It looks like it's possible to get the crate name by running "cargo metadata" after adding the dependency to Cargo.toml. e.g.:

```json
 {
            "name": "prettytable-rs",
            "targets": [
                {
                    "kind": ["lib"],
                    "crate_types": ["lib"],
                    "name": "prettytable",
                },
            ],
}
```

So that would be one option to fix the \:dep command.

As Celti mentioned on #21, we probably want to think about how this will look once 2018 is stable.

I suppose separating \:dep and extern crate would fix this, albeit at the cost of users having to write both for every crate they import. Then later "use" instead of "extern crate".
