### ISSUE TITLE
Where are the errors and print! not working 

### ISSUE THREAD

**Issue by Tros-t** [google/evcxr#157]
Hi, 
Loved the main thing but I cannot see my errors 
when I run 
`a = 5` without defining a it doesn't gives me any error just prints 5 out.

And when I try to print something without the ln or just `print!("hi");` it doesn't print anything to the output area.

And do you guys have any ideas to make this a bit faster

**Comment by bjorn3** [comment]
`print!()` without `ln` doesn't flush the stdout buffer. libstd only writes to the OS stdout every time it sees a newline. That is stdout is line buffered.

**Comment by davidlattimore** [comment]
Thanks for the report @Saad-py. That's interesting that `a=5` doesn't error. What's happening is that because it doesn't end in a semicolon, it's treated as an expression and evcxr tries to print expressions. You can imagine it taking your code and wrapping it as `println!("{}", a = 5);`... which compiles. I think in order to make this code produce an error, I'd probably need to explicitly check for it.

But rest assured, errors should in general be displayed. For example if you do `a = 5;` then you get:

```
>> a = 5;
   ^ not found in this scope
cannot find value `a` in this scope
```

**Comment by bjorn3** [comment]
Could you write `println!("{}", &(a=5));` ibstead of `println!("{}", a=5);` for `a=5`? That should avoid interpreting `a=` by `println!()` instead of as assignment.

**Comment by hatzkel** [comment]
Could it be you are placing the code in the notebook cells within a  main() function? 

If you put the code inside 

fn main() {
...
} 
and then run it you will not see these. I made that mistake when playing with initially.

**Comment by davidlattimore** [comment]
With the above commit, an error is now show as expected.

```
>> a = 5
   ^ not found in this scope
cannot find value `a` in this scope
```
