### ISSUE TITLE
[Help] Wanted to create eval command

### ISSUE THREAD

**Issue by Daggy1234** [google/evcxr#163]
Hey evcxr team!

I was told in the crates.io repo to create an issue if I needed help with a usecase. So I made a discord bot in rust and would very much like to be able to evaluate rust code from discord. The way this would work is I would have a vec of strings that contain each line of my rust code.. I would then assemble that code into a single string. I would then like to use the `EvalContext` and evaluate the code, sending the output or any error. My main issues are as follows:

1) How do I get the output/error
2) How will this work given my app is asynchronous (tokio )
3)  what does this mean`evcxr::runtime_hook() `, and why at the top of main?

**Comment by bjorn3** [comment]
> 2. How will this work given my app is asynchronous (tokio )

Evcxr is synchronous, so it will block until the code is executed.

> 3. what does this mean `evcxr::runtime_hook()`, and why at the top of main?

The function has a doc comment:

https://github.com/google/evcxr/blob/3464f7b931f53d54b24c5a451a26aa9571e7fb57/evcxr/src/runtime.rs#L26-L32

Honestly I don't think evcxr is very suitable for the discord bot you want to build. Evcxr has a lot of complexity to deal with preserving variables across individual invocations. In your case simply wrapping the code in `fn main() { println!("{:?}", { ` and ` }); }` and then directly invoking rustc should work fine. If you also want to support crates from crates.io, you may do something like the rust playground ([source](https://github.com/integer32llc/rust-playground)): Take the top 100 crates and add them as fixed dependency to a cargo project. This cargo project is then compiled once to compile all dependencies. The compiled dependencies can then be re-used for each code snippet.

**Comment by davidlattimore** [comment]
Hi @Daggy1234 - I'd second what @bjorn3 said that assuming you don't need variables to be preserved between executions, you'd be better off with something a lot simpler.

But to add more detail about `runtime_hook`, evcxr starts a subprocess in which to run the code. That subprocess can either be the same binary as the one using `evcxr::EvalContext` or a separate binary. Either way, the binary that gets launched as the subprocess needs to call `runtime_hook` pretty much at the start of main. If `runtime_hook` detects that it's not running as a subprocess (it checks to see if some environment variable is set), then it just returns, otherwise it enters a control loop where it receives commands from the parent process.

If you call `EvalContext::new`, then the binary that you call it from must call `runtime_hook` as early as possible in main. If that's not an option, you can supply a separate binary for launching the subprocess. That separate binary needs to call `runtime_hook`. You can then use `EvalContext::with_subprocess_command`.

**Comment by davidB** [comment]
For a set of [lessons](https://github.com/davidB/hello_rs_overdesign) I gave few year ago, I got a similar need "running a single rs with deps". I used [cargo-script](https://crates.io/crates/cargo-script), maybe it will better suit your need + wrapper,...

**Comment by Daggy1234** [comment]
Thank you everyone. Yeah rustc and a file based approach is much better. Thanks!
