### ISSUE TITLE
Evcxr freezes with no explanation

### ISSUE THREAD

**Issue by richardanaya** [google/evcxr#166]
I must be missing something really basic, but this doesn't work:

```
use evcxr::*;
fn main() -> Result<(), evcxr::Error>{
    evcxr::runtime_hook();
    let (mut context,_) = EvalContext::new()?;
    context.eval("let s = String::new();")?;
    context.eval(r#"s.push_str("Hello ");"#)?;
    context.eval(r#"s.push_str("World");"#)?;
    context.eval(r#"println!("{}", s);"#)?;

    Ok(())
}
```

the app just freezes. This is on Rust 1.51 ubuntu linux

specifically it freezes on ` EvalContext::new()`

**Comment by davidlattimore** [comment]
It probably is running, but is just really really slowly. Evcxr uses rust-analyzer, which pretty much needs optimization enabled in order to function.

I have the following in my Cargo.toml so that I get optimization even for non-release builds:

```toml
[profile.dev]
opt-level = 2
```

Otherwise, it's worth mentioning that stdout from the evaluation context won't go to your stdout. It goes to the `EvalContextOutputs` that is the second return value from `EvalContext::new()`. The following code runs as expected:

```rust
use evcxr::*;

fn main() -> Result<(), evcxr::Error>{
    evcxr::runtime_hook();
    let (mut context, outputs) = EvalContext::new()?;
    context.eval("let mut s = String::new();")?;
    context.eval(r#"s.push_str("Hello ");"#)?;
    context.eval(r#"s.push_str("World");"#)?;
    context.eval(r#"println!("{}", s);"#)?;

    // Dropping `context` shuts it down, otherwise the loop that follows will continue to wait in
    // case the context sends more output.
    drop(context);

    while let Ok(line) = outputs.stdout.recv() {
        println!("{}", line);
    }

    Ok(())
}
```

**Comment by richardanaya** [comment]
oh wow, it was just slow,your code worked!
