### ISSUE TITLE
Rust kernel with a custom name

### ISSUE THREAD

**Issue by jornfranke** [google/evcxr#247]
Hallo,

I have configured evcxr in Jupyterlabv3 successfully. I use a micromamba environment and it works perfectly fine. /I have a custom kernel name ("Rust Micromamba") in Jupyterlab and this works also fine. 

However, every time I start the kernel it seems evcxr creates another kernel in Jupyterlab with the name rust, which I do not need and which also does not run as it contrary to my custom kernel does not activate my custom micromamba environment.
Can you make it configurable if evcxr creates this default kernel "Rust" or not?

Thanks a lot

Best regards

**Comment by davidlattimore** [comment]
Hi @jornfranke. The Rust kernel is registered when you run `evcxr_jupyter --install`. So long as you're not running that every time your custom kernel starts, it shouldn't be creating anything. But possibly I'm misunderstanding what you're seeing

**Comment by davidlattimore** [comment]
Ah, I see. You're quite right. I'd forgotten that I did that! I've changed it so that if the kernel directory doesn't already exist, it will skip automatically "updating" it. Also happy to have a flag if that isn't sufficient for some reason. Thanks for reporting and thanks for your patience with my erm... forgetfulness
