### ISSUE TITLE
Rust doesn't support interrupting execution. Perhaps restart kernel?

### ISSUE THREAD

**Issue by davidyew** [google/evcxr#248]
Hi!

I installed evcxr_jupyter 0.14.0, jupter 3.4.7, rust 1.64.0 and encountered errors.
Hope to get some advise please.

Extracting some of the useful logs here
[I 2022-09-24 12:04:08.703 LabApp] Build is up to date
[I 2022-09-24 12:04:10.075 ServerApp] Kernel started: 5d736e0b-413d-47c9-b682-97163e6e01e1
Error: "{UserPath}\\.cargo" "--version" failed
[I 2022-09-24 12:04:13.022 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
Rust doesn't support interrupting execution. Perhaps restart kernel?
Error: "{UserPath}\\.cargo" "--version" failed
[I 2022-09-24 12:04:16.063 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (2/5), new random ports
Error: "{UserPath}\\.cargo" "--version" failed
[I 2022-09-24 12:04:19.087 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (3/5), new random ports
Error: "{UserPath}\\.cargo" "--version" failed
[I 2022-09-24 12:04:22.136 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (4/5), new random ports
Error: "{UserPath}\\.cargo" "--version" failed
[I 2022-09-24 12:04:25.179 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
Error: "{UserPath}\\.cargo" "--version" failed
[W 2022-09-24 12:04:28.217 ServerApp] AsyncIOLoopKernelRestarter: restart failed
[W 2022-09-24 12:04:28.217 ServerApp] Kernel 5d736e0b-413d-47c9-b682-97163e6e01e1 died, removing from map.

**Comment by davidlattimore** [comment]
Hi @davidyew. The bit about "Rust doesn't support interrupting execution" is just a warning, not an error, so I don't think that's the problem, although I should perhaps remove that warning to avoid confusion.

It looks like the error is `"{UserPath}\.cargo" "--version" failed`. I'm not quite sure what that is, since `--version` doesn't exist anywhere in the evcxr code, so I don't think evcxr is invoking that command, but rather a subprocess like carg is. Plausibly a change that I made recently in how evcxr invokes cargo or another change I made to alter the way cargo invokes rustc (both performance optimisations).

What OS are you on?

Was this a precompiled binary from the releases page, or did you build yourself (with `cargo install`)? The precompiled binaries are new in 0.14.0, so it's entirely possible I'm building them wrongly.

Also, have you previously been able to use `evcxr_jupyter` OK, or is this your first attempt to use it? Helpful in judging if this is a regression

**Comment by bjorn3** [comment]
Did you set the `CARGO` env var to `{UserPath}\.cargo`? It needs to point to the cargo executable or unset entirely if cargo is already in your `PATH`.

> m not quite sure what that is, since --version doesn't exist anywhere in the evcxr code, so I don't think evcxr is invoking that command, but rather a subprocess like carg is.

Rust-analyzer does this.

**Comment by davidyew** [comment]
Hi @davidlattimore , thank you for helping! I am on Windows 10.

Hi @bjorn3 , thank you for replying too! You hit the nail on the head! I had set CARGO env var wrongly!

It is working now!
