### ISSUE TITLE
Evcxr_jupyter kernel can not work in vscode jupyter extension.

### ISSUE THREAD

**Issue by baiguoname** [google/evcxr#255]
In my computer, evcxr_jupyter works well in jupyter lab. But when I use it in vscode, it nerver can connect the jupyter kernnel(named by evcxr_jupyter.exe in vscode). As can be seen below:
![image](https://user-images.githubusercontent.com/52092777/204957451-5ee304c5-8d83-439c-898e-73c868ac4479.png)

The first cell (input 1) would never finish.

**Comment by haroonsyed** [comment]
I can also confirm this issue.

Running on windows 11. 
VSCode v1.74.2
Jupyter(vscode extension) v2022.11.1003412109
rustc v1.66.0
evcxr_jupyter (latest release as of 12/20/22)

**Comment by TethysSvensson** [comment]
I'm running on NixOS and it is also broken in vscode for me.

I noticed that only v0.14.1 is broken, while v0.14.0 works. I did a git bisect to find out when it started breaking.

The result is that the first bad commit is c8d0f44. I am going to stay on v0.14.0 for now.

**Comment by davidlattimore** [comment]
Thanks all, especially @TethysSvensson for bisecting it. That's a great help! I'd never tried using the vscode Jupyter extension before.

In that commit, it was the change to the current_thread executor that broke things. Using the multi-threaded executor makes it work, strangely even with a single thread. Alternatively, adding a sleep, even a 1 microsecond sleep anywhere in the `handle_shell` loop also "fixes" the problem.

It looks like what's happening is that vscode's jupyter extension is connecting to the kernel on the various sockets, then sending messages on the shell socket before the `iopub` socket has finished connecting. The kernel sends `execution_state="idle"` messages on the `iopub` socket, but because there are no subscribers yet to the iopub, these messages go nowhere. The iopub connection then gets processed and the extension waits for `execution_state="idle"`, but it will never come because it was already sent before the subscription was processed.

I'll switch back to the multithreaded executor. I think even then the problem could in theory occur, although it hopefully won't in practice.

**Comment by TethysSvensson** [comment]
@davidlattimore Would you mind doing a new release with this?

**Comment by TethysSvensson** [comment]
@davidlattimore Thanks!
