### ISSUE TITLE
Closure problems and 'pub'  needed

### ISSUE THREAD

**Issue by happydpc** [google/evcxr#45]
When the expression is not started with pub, then it will just show the warning. How about we default make it as 'pub' visibility?

When the expression is closure function, it will show the error "unknown start of token: \" and any expression later will be the same error.

![tim 20190305115358](https://user-images.githubusercontent.com/771776/53780049-8cd78400-3f3d-11e9-9bfe-1e2f4e5a6c77.png)

**Comment by davidlattimore** [comment]
Hi. Thanks for the feedback. For info on adding pub, see #10. Regarding closures, that unfortunately won't be possible to support, since we can only store variables with types that can be named and you can't name the type of a closure. Perhaps if you can box the closure as a trait object it can be stored. The error message when you do this is indeed terrible. I'd not thought to try this so hadn't seen it before. Thanks for pointing it out. I'll keep this bug open to improve the error message.

**Comment by davidlattimore** [comment]
With release 0.4.0 and onwards, I changed the execution model that Evcxr uses, so that all code is now a single crate instead of a separate crate for each bit of code. As a result, pub is no longer needed :)
