### ISSUE TITLE
Importing files with "mod" does not work

### ISSUE THREAD

**Issue by x3pi** [google/evcxr#70]
```
mod hello;
    ^^^^^ 
file not found for module 'hello'
```

I used the "mod" keyword to import files, but it didn't work. How to solve this problem.

**Comment by davidlattimore** [comment]
Interesting. I'd not thought of trying that. It'd be a bit tricky to make it work, since the code you write gets written to a file in a temporary directory, so it can't easily reference the code in the directory in which you ran evcxr. You can pull in your code as a crate though. For example:
:dep hello = { path = "." }

Replace "hello" with whatever the name your crate is. When it does this, evcxr interprets the path as relative to where you launched evcxr and rewrites it as an absolute path.

You'll only be able to reference pub items.

Adding support for mod is an interesting idea. I'm somewhat unsure of how it would work though. Especially if the loaded mod depended on stuff from the root of the crate in which it was defined. I'd have to give that some thought.
