### ISSUE TITLE
Document supported rust versions

### ISSUE THREAD

**Issue by thomcc** [google/evcxr#80]
I noticed https://github.com/google/evcxr/blob/986c3e6aed455fecf9a883ff2a47e74411cc0c35/evcxr/src/crate_config.rs#L34, which indicates some older versions of rustc are supported. Which versions doesn't seem documented anywhere though.

The ideal "documentation" for this is likely just to include the version in https://github.com/google/evcxr/blob/master/.travis.yml.

**Comment by davidlattimore** [comment]
Thanks for pointing that out. That comment is now pretty old, and we've now long dropped support for those old versions. They were pretty hard to keep support for, since if any transitive dependency used custom derive, then it'd break. I've updated the comment, plus a couple of other similar comments.

I've also tested what the current minimum version of rustc that evcxr works with. Seems like it's 1.36.0. I'll add that to the travis config (and my release script). Good idea.
